# -*- coding: utf-8 -*-
"""app start-stop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HD23CWASTUUlGnOJXsOy0WYID2JXkMbI
"""

pip install streamlit

import streamlit as st
import pandas as pd

# Cargar el archivo de Excel
uploaded_file = st.file_uploader("Sube el archivo Excel con los medicamentos", type="xlsx")

if uploaded_file is not None:
    # Leer el archivo Excel en un DataFrame
    df = pd.read_excel(uploaded_file)

    # Mostrar las primeras filas para verificar que se ha cargado correctamente
    st.write("Datos cargados con éxito:")
    st.dataframe(df.head())

    # Input del usuario para buscar un medicamento
    medicamento = st.text_input("Introduce el nombre del medicamento:")

    # Función para obtener START y STOP de un medicamento
    def obtener_start_stop(medicamento):
        # Buscar si el medicamento está en el DataFrame
        resultado = df[df['Medicamento'].str.contains(medicamento, case=False)]

        # Si el medicamento no se encuentra, devolver mensaje
        if resultado.empty:
            return f"El medicamento '{medicamento}' no se encuentra en la base de datos."

        # Obtener los valores de las columnas START y STOP
        start = resultado['START'].values[0]
        stop = resultado['STOP'].values[0]

        return f"Medicamento: {medicamento}\nSTART: {start}\nSTOP: {stop}"

    # Mostrar el resultado de la búsqueda si se introduce un medicamento
    if medicamento:
        resultado = obtener_start_stop(medicamento)
        st.write(resultado)

streamlit run app.py